const bollywood = [{
    id:1,
    image:"https://assets.telegraphindia.com/telegraph/2023/May/1685180682_naseeb-se.jpg",
    heading:"Satyaprem Ki Katha: Kartik Aaryan, Kiara Advani shine in this pure love story on a sensitive subject",
    description:"Kartik Aaryan and Kiara Advani deliver stellar performance in his romantic comedy with a beating heart.",
    content:"It's been quite some time I hadn't seen a sweet, endearing and pure love story that has its heart at the right place, coming out from Bollywood. While I entered Satyaprem Ki Katha hoping it'll be one, turns out it's much more than just a simple love story. Using the canvas of a love story, director Sameer Vidwans addresses an important issue that has plagued our society for long, and in the process, he blends raw emotions of the young generation, conservative outlook of the elderly, and the shame that middle-class lot has for long lived with. With a brilliant story and idea in hand, the film falters at places with its execution, though it's never to an extent that it takes away from the purity of the story. A musical romance with a good-looking lead pair -- Kartik Aaryan and Kiara Advani -- who have earlier also made heads turn with their chemistry in Bhool Bhulaiyaa 2 - Satyaprem Ki Katha is refreshing, entertaining but never lets go of the sensitivity of the subject at hand.",
    category:"Bollywood",
},
{
    id:2,
    image:"https://www.bollywoodhungama.com/wp-content/uploads/2023/04/IB71-Feature.jpg",
    heading:"IB71",
    description:"IB71 is based on the true story of the 1971 Indian Airlines hijacking. It is written and directed by Sankalp Reddy.",
    content:"In 1971, the Indian Intelligence Bureau receives critical information about Pakistan and China's impending attacks on India within 10 days. With limited time and resources, IB agent Dev Jammwal tells his superior N.S. Avasti that the only plan to counter this threat is by implementing an airspace blockade, which blocked Indian airspace access to Pakistan and tried to show the violation of the Tashkent Agreement, which involves orchestrating the hijacking of an Indian plane by Kashmiri separatists and ensuring its landing in Pakistani territory. Initially dismissed as an implausible scheme by the government, they eventually recognize its potential and agree to execute the well-structured operation. Complications arise when the entire team of passengers, comprising intelligence officers, find themselves lodged in a Lahore hotel, where events unfold in an unforeseen circumanstances, thus deviating from the original plan.",
    category:"Bollywood",
},
{
    id:3,
    image:"https://static-koimoi.akamaized.net/wp-content/new-galleries/2023/06/bloody-daddy-movie-review-002.jpg",
    heading:"Bloody Daddy",
    description:"Bloody Daddy is a 2023 Indian Hindi-language action thriller film directed by Ali Abbas Zafar and produced by Jio Studios.",
    content:"Bloody Daddy is a 2023 Indian Hindi-language action thriller film directed by Ali Abbas Zafar who co-wrote the film with Aditya Basu and Siddharth–Garima, and produced by Jio Studios. It features Shahid Kapoor, Sanjay Kapoor, Diana Penty, Ronit Roy, Rajeev Khandelwal, Ankur Bhatia and Vivan Bhatena.Sumair Azad is an NCB officer, who along with his deputy Jagadish Prasad alias Jaggi in Gurugram bust down a drug deal, leading the drug lord Sikandar to kidnap Sumair's son Atharva in exchange for retrieving the bag of cocaine. With no other option left, Sumair agrees to retrieve the bag from the NCB headquarters, and bring it to his club for the exchange. Sumair's act of hiding the bag in the men's toilet is noticed by his assistant Aditi Rawat, who becomes suspicious. Thinking that Sumair is involved in drug smuggling, Aditi informs her superior Sameer Singh and begin to pursue Sumair, taking away the bag of cocaine from the toilet in the process.",
    category:"Bollywood",
},
{
    id:4,
    image:"https://assets-in.bmscdn.com/discovery-catalog/events/et00347237-zvaqglepzw-landscape.jpg",
    heading:"Tu Jhoothi Main Makkaar",
    description:" Indian Hindi-language romantic comedy film directed by Luv Ranjan and written by Rahul Mody and Ranjan.",
    content:"Rohan 'Mickey' Arora is the son of Ramesh Arora, a rich Punjabi business magnate, and lives with his family in Delhi. He and his best friend Manu Dabbas secretly work as break-up consultants, helping people break-up with their respective partners. Mickey and Manu travel to Spain for Manu's bachelor party, where they are accompanied by Manu's fiancèe Kinchi, along with her best friend Nisha 'Tinni' Malhotra. Mickey and Tinni hook up and eventually fall in love with each other. Upon returning, Manu and Kinchi get married, while Mickey and Tinni introduce each other to their respective families. Both the families accept their relationship and start preparations for their wedding. However, Tinni feels she is not ready for the marriage and decides to breakup with Mickey. Tinni contacts the break-up consultant on phone, not knowing that it is in fact Mickey, and asks for help in breaking up with him. Unaware that he is speaking with Tinni, Mickey agrees to help.",
    category:"Bollywood",
}
]

const hollywood = [
    {
    id:5,
    image:"https://static-koimoi.akamaized.net/wp-content/new-galleries/2023/08/stream-spider-man-across-the-spider-verse-from-8th-august-2023-on-zee5-01.jpg",
    heading:"Spider-Man: Across the Spider-Verse To Premiere On Zee5 This Week",
    description:"ZEE5, India’s largest home-grown video-streaming platform and a multilingual storyteller, announced the digital premiere date of the global hit film ‘Spider-Man: Across the Spider-Verse’.",
    content:"Premiere Date 08 August. Spider-Man fans, rejoice! The much-awaited sequel to the Oscar-winning animated film, Spider-Man: Across the Spider-Verse, is making its grand entrance on ZEE5. Mark your calendars, as the premiere date is set for August 8, 2023.Wondering where to watch Spider-Man: Across the Spider-Verse? ZEE5, India’s largest home-grown platform, has secured exclusive streaming rights, and the excitement is building. Don’t miss out on what’s sure to be an unforgettable experience.",
    category:"Hollywood",
},
{
    id:6,
    image:"https://www.hindustantimes.com/ht-img/img/2023/08/06/550x309/Celebrity-Birthdays---July-30---Aug--5-0_1691346360015_1691346405354.jpg",
    heading:"Barbie's Greta Gerwig is first women director to enter Hollywood's billionaire club, film earns $1bn",
    description:"Greta Gerwig's Barbie becomes first women directed Hollywood film to earn $1 billion worldwide.",
    content:"The year's highest-grossing film (so far), 'The Super Mario Bros. Movie', accomplished that feat in April after four weeks. Barbie makes Gerwig the 29th director, and the first solo female director, to join the billion-dollar club.'Barbie', directed by Greta Gerwig, surpasses the $1 billion mark at the global box office, becoming the second film this year to achieve that milestone. This is the first film led by a female director to achieve this milestone.",
    category:"Hollywood",
},{
    id:7,
    image:"https://www.hindustantimes.com/ht-img/img/2023/08/06/550x309/rwrb_1691333325649_1691333326035.png",
    heading:"Red, White and Royal Blue director Matthew López on that coming out scene",
    description:"In a chat with Hindustan Times, Matthew López shared how he cannot imagine the film without its two leading actors Taylor Zakhar Perez and Nicholas Galitzine.",
    content:"In a chat with Hindustan Times, Matthew López shared how he cannot imagine the film without its two leading actors Taylor Zakhar Perez and Nicholas Galitzine.The much-awaited adaptation of Red, White and Royal Blue, Casey McQuiston's bestselling LGBTQ+ romance, is all set to premiere on Prime Video on August 11. Taylor Zakhar Perez and Nicholas Galitzine play Alex Claremont-Diaz, the son of the president of the United States, and Prince Henry of Wales respectively, who end up tripping over a giant cake together first and then come around to fall in love with each other.",
    category:"Hollywood",
},{
    id:8,
    image:"https://images.thequint.com/thequint%2F2023-06%2Fa135d749-cff2-4f5a-87a8-57b6f39e63d5%2F354408870_472267618455335_6217375107344874925_n.jpg",
    heading:"Gal Gadot interview: Alia Bhatt is ‘super ready’ to break into Hollywood",
    description:"In an exclusive interview, Gal Gadot discusses working with Alia Bhatt, making waves in Hollywood as an Isaraeli actor, and performing action in Heart of Stone.",
    content:"Breaking into the American market is going to be a smooth, healthy evolution or transition for Alia. I think she's super ready. If she ever needs anything, she's my buddy, she's my sister, she has my number, she has my address. I'm always here for her,” Gal added.Gal is quite confident that Alia is equipped enough to make inroads into Hollywood on her own. “I don't think Alia needs any word of advice. She comes with such experience, working for over a decade in India. And India, you guys are massive! So she knows how to handle the heat. ",
    category:"Hollywood",
}]

const fitness = [
    {
        id:51,
        image:"https://royalsuiteshealthcare.blog/wp-content/uploads/2017/08/exercise-1.jpg",
        heading:"Exercise Among Older Adults Boosts Brain Power",
        description:"Encouraging older adults to engage in regular exercise can significantly support and enhance cognitive function as per a study at the University of Tsukuba and the University of California, Irvine.",
        content:"Many senior adults spend a lot of time on performing exercises and mindfulness training as they get older. However, a new large study that focus on their effectiveness on cognitive function has found no such improvement. Researchers at Washington University School of Medicine in St. Louis and the University of California, San Diego, studied the cognitive effects of exercise, mindfulness training or both for up to 18 months in older adults who reported age-related changes in memory but had not been diagnosed with any form of dementia.Many senior adults spend a lot of time on performing exercises and mindfulness training as they get older. However, a new large study that focus on their effectiveness on cognitive function has found no such improvement. Researchers at Washington University School of Medicine in St. Louis and the University of California, San Diego, studied the cognitive effects of exercise, mindfulness training or both for up to 18 months in older adults who reported age-related changes in memory but had not been diagnosed with any form of dementia.",
        category:"Fitness",
    },{
        id:52,
        image:"https://images.newscientist.com/wp-content/uploads/2023/05/23171152/SEI_157358778.jpg?width=900",
        heading:"‘Shin splints’ may not be caused by running up and down hills",
        description:"Shin pain is common for runners, but it's unclear what parts of training most contribute. ",
        content:"Shin pain is common for runners, but it's unclear what parts of training most contribute. It turns out that pressure on shin bones is more severe when runners up their pace compared to when they train on hills. Runners may face a greater risk of developing fractures in their shin bones when they run quickly, compared with when they run uphill or downhill.The repetitive pounding motion of running can lead to painful overuse injuries known as “shin splints” and even fractures in runners’ shin bones. Researchers know that these fractures often happen when runners increase the intensity of their training, but it isn’t well understood which aspects …",
        category:"Fitness",    
    },{
        id:53,
        image:"https://community.thriveglobal.com/wp-content/uploads/2020/08/brain-training.png",
        heading:"Reclaim Cognitive Vitality Through Brain Fitness Program",
        description:"Groundbreaking study led by GWU professor unveils transformative 'brain fitness program' for individuals.",
        content:"With the Medicare enrollment period now closed, federal data show that memory fitness – what some call “brain training” – is the fastest growing Medicare Advantage fitness benefit.Memory exercises are now offered by more than 25 percent of plans that offer fitness benefits, frequently tied to gym memberships.While the perk may seem brand new to some – Medicare only approved memory training’s inclusion in plans in 2019 – it marks a fairly long and torturous road for Henry Mahncke, a neuroscientist who for decades has been studying how to improve cognitive function.",
        category:"Fitness",
    },{
        id:54,
        image:"https://media.istockphoto.com/id/491267846/photo/doing-crane-position-by-the-beautiful-view.jpg?s=612x612&w=0&k=20&c=tJocdWfLM5-QSAA4FBU_9S6eCXRUAG4z9EttDp2Cn8s=",
        heading:"Embrace Nature and Wellness: Discover the Magic of Outdoor Yoga",
        description:"Outdoor yoga allows you to merge the wisdom of yoga with the soothing effects of nature, fostering a deep sense of connection and grounding.",
        content:"It’s summer now in this beautiful region of rolling hills I call home. And during this gorgeous and (for me) all-too-fleeting season, my thoughts turn to getting outdoors as much as possible—and that includes for yoga practice.Practicing outdoors certainly has many advantages, ranging from health benefits to the simple enjoyment of a change of scenery. But before you stride boldly off into the forest for some flow en plein air, there are a few things to take into consideration. These are important not only for solo practitioners, but also for teachers who are thinking of teaching outdoor 'yoga in the park' type classes.",
        category:"Fitness",
    },{
        id:55,           
        image:"https://www.endocrine.org/-/media/endocrine/images/patient-engagement-webpage/condition-page-images/diabetes-and-glucose-metabolism/diabetes_treatments_pe_1796x9432.jpg",
        heading:"Healthier Path: Light Exercise for Dialysis Patients",
        description:"According to a comprehensive study led by the Technical University of Munich (TUM), dialysis patients who incorporate light exercise into their routines experience enhanced physical fitness and reduced hospital admissions.",
        content:"Exercise is important for people on dialysis because it promotes a healthier lifestyle. Exercise can help you in numerous ways. If you are overweight and your doctor suggests that you lose extra pounds, exercise – along with a lower-calorie, kidney-friendly diet – can help. You can also strengthen your muscles with exercise. One of the most important muscles to exercise is your heart. A healthy heart is important, because when you have kidney disease you are at risk for getting heart disease. Exercise can also reduce depression and help you feel happier.",
        category:"Fitness",
    },{
        id:56,
        image:"https://cdn.who.int/media/images/default-source/campaigns---walk-the-talk/walk-the-talk/wtt-geneva-2023/wtt2023-crowd-hq139410.jpg?sfvrsn=bae91ad8_3",
        heading:"More than 7000 join the 4th edition of Walk the Talk in Geneva: Health for All Challenge",
        description:"WHO together with Swiss and Geneva partners, the UN family, Member States, athletes, local sports clubs, and health partners came together on Sunday 21 May 2023.",
        content:"WHO together with Swiss and Geneva partners, the UN family, Member States, athletes, local sports clubs, and health partners came together on Sunday 21 May 2023, to celebrate the importance of healthy lifestyles and to kick off the Seventy-sixth World Health Assembly.I am very happy to see so many people from all over the world today for our fourth Walk the Talk: Health for All challenge. This day is also an opportunity to come together to celebrate our shared commitment to health for all, our work to address the challenges posed by the COVID-19 pandemic and to celebrate WHO's 75th anniversary,Dr Tedros told the crowd.",
        category:"Fitness",
    },{
        id:57,
        image:"https://d2jx2rerrg6sh3.cloudfront.net/image-handler/ts/20200217100539/ri/673/picture/2020/2/%40shutterstock_779710966.jpg",
        heading:"Why You Should Exercise in the Morning",
        description:"According to scientific literature, exercising in the morning is more beneficial than exercising at night. The better outcome is associated with improved management of metabolic pathways and energy homeostasis.",
        content:"Exercising in the morning has more health benefits than the obvious ones. Besides burning calories, working out in the morning can also Encourage you to eat healthier, Boost your energy throughout the day, Improve focus and cognition, Put you in a better mood, Lower your risk for diabetes, Help you sleep better.",
        category:"Fitness",
    },{
        id:58,
        image:"http://content.health.harvard.edu/wp-content/uploads/2023/07/9234d464-594b-468a-b9ac-c37e16c6af3a.jpg",
        heading:"Try this: Swinging with kettlebells",
        description:"Want to give your workouts a lift? Pick up a kettlebell. This versatile exercise tool resembles a cannonball with a handle on top and ranges in weight from 5 to 30-plus pounds.",
        content:"Kettlebell swings are a strength-training exercise that, unsurprisingly, requires a kettlebell. A kettlebell is a type of cast-iron or steel weight with a flat base and a handle for gripping. It looks like a cannonball with a handle or a tea kettle. Hence, the name. The total-body move involves gripping the handle of the weight with both hands and using explosive power from the hips and thighs to swing the weight up to about chest height. A standard or Russian kettlebell swing works multiple muscles.",
        category:"Fitness",
    },{
        id:59,
        image:"https://i0.wp.com/www.eastmojo.com/wp-content/uploads/2022/12/pexels-alex-green-5693065.jpg?fit=1200%2C814&ssl=1",
        heading:"Short bursts of daily activity linked to reduced cancer risk",
        description:"Promising new research suggests a total of just 4.5 minutes of vigorous activity that could reduce the risk of some cancers by up to 32 percent.",
        content:"Short Bursts of Vigorous Daily Activity May Be Linked to Reduced Cancer Incidence. Investigators have found that just 4.5 minutes of vigorous activity per day could reduce the risk of some cancer types by up to 32%. The results of the recent study were published by Stamatakis et al in JAMA Oncology.Vigorous intermittent lifestyle physical activity describes very short bursts of activity—around 1 minute each—and includes activities such as doing vigorous housework, carrying heavy groceries around the supermarket, power walking, and playing high-energy games.",
        category:"FitSide",
    },{
        id:60,
        image:"https://www.hindustantimes.com/ht-img/img/2023/08/05/550x309/pexels-kampus-production-8188746_1691224057624_1691224079766.jpg",
        heading:"Actor and fitness enthusiast Pranitha Subhash shares 3 health-focused tips",
        description:"Kannada actor Pranitha Subhash suggests going beyond the traditional gestures this weekend to care for our fathers.",
        content:"In a world filled with fleeting moments and transient relationships, there is one constant presence that remains unwavering—the love of a father where through the ups and downs, the laughter and tears, a father's love is a steady anchor, grounding us in a world that can often feel uncertain. It is a love that nurtures, guides and supports us, shaping us into the person we become.The role of a father is multifaceted and one aspect that often goes unnoticed is their dedication to staying fit and healthy. In an interview with HT Lifestyle, Kannada actor Pranitha Subhash suggested going beyond the traditional gestures this weekend and taking a step further to promise our fathers something truly meaningful by taking extra care for their well-being.",
        category:"FitSide",
    },{
        id:61,
        image:"https://femina.wwmindia.com/content/2021/jan/components-of-physical-fitness-infographic.jpg",
        heading:"SBP Coaches Focusing On Physical Fitness",
        description:"Expert coaches continued to impart modern training to young participants at Sports board Punjab (SBP).",
        content:"LAHORE, (APP - UrduPoint / Pakistan Point News - 7th Aug, 2023 ) :Expert coaches continued to impart modern training to young participants at Sports board Punjab (SBP) High Performance Tennis Training Camp here at state-of-the-art Tennis Courts on Monday.Director General Sports Punjab Dr Asif Tufail said that a large numbers of boys and girls of different age groups are participating in the month-long camp being organised under the supervision of qualified coaches till August 31. 'Besides routine training, special emphasis is being given on physical fitness of young male and female camp probables'.",
        category:"FitSide",
    },{
        id:62,
        image:"https://steelfitusa.com/cdn/shop/articles/Calories-Burnt-While-Lifting-Weights-SteelFit.jpg?v=1626711296&width=800",
        heading:"How Many Calories Do You Burn Lifting Weights?",
        // description:"Weight loss is ultimately about calories in versus calories out.So long as you expend more calories in a day than you consume, you will lose weight.",
        content:"Beyond the typical goal of increasing muscle, weightlifting is linked to several positive health effects, one of which is the capacity to burn calories both during and after workouts.The number of calories burned during a weightlifting session depends on a number of variables, including the person's weight, their percentage of lean muscle mass, the exercises they are doing, the number of sets and repetitions they are doing, and how hard the lifting session is.Burning calories is a common worry when it comes to weight loss, or more specifically, fat loss. ",
        category:"ToppostsFit",}
]

const food = [{
    id:6,
    image:"https://media.cnn.com/api/v1/images/stellar/prod/181127110351-18-50-sweets-travel-tiramisu.jpg?q=w_2391,h_1345,x_0,y_0,c_fill/h_618",
    heading:"Tiramisu, Italian dessert",
    content:"Tiramisu appears to have been invented in the 1960s, but where and when exactly is unclear. Some believe the recipe was modeled after sbatudin, a simpler dessert made of egg yolks and sugar.Others argue it originated from another dish, dolce Torino.The recipe for tiramisu is not found in cookbooks before the 1960s. It is mentioned in a Sydney Morning Herald restaurant column published in 1978. It is not mentioned in encyclopedias and dictionaries of the 1970s, first appearing in an Italian dictionary in 1980, and in English in 1982. It is mentioned in a 1983 cookbook devoted to cooking of the Veneto.",
    description:"Creamy layers of whipped mascarpone cradle coffee-soaked ladyfingers in this modern Italian dessert, which has become a sweet mainstay around the globe.",
    category:"Food",
},
{
    id:7,
    image:"https://www.sharmispassions.com/wp-content/uploads/2020/03/WhiteSaucePasta6-500x375.jpg",
    heading:"White Sauce Pasta",
    description:"White Sauce Pasta is very easy to prepare along with a mix of colorful vegetables it is whole some and nutritious too.",
    content:"White Sauce Pasta (also referred to as White Pasta) is one of the most popular and easiest pasta recipes that you can make at home. In this White Sauce Pasta Recipe, I am sharing an easy way to make a restaurant style white sauce (or béchamel sauce) in which cooked penne pasta is tossed. The recipe comes together in 30 minutes and makes for a comforting brunch or lunch.This popular White Sauce Pasta Recipe is a vegetarian version and can be served as a snack or light dinner. You can make it more wholesome and hearty by adding some mixed vegetables. Adding mixed veggies to this pasta dish is a great way to get your family to consume more nutrition along with flavors. These vegetables can be steamed, cooked, sautéed or roasted.",
    category:"Food",
},
{
    id:8,
    image:"https://cdn.pixabay.com/photo/2016/08/01/17/08/tomatoes-1561565_1280.jpg",
    heading:"Tomato price hits household budget hard, cost of vegetarian thali rose by 34% in July",
    // description:"A recent research by consultancy firm Crisil has shown that in the past 17 months or so, the cost of vegetarian thali in the Indian households has risen from Rs 24.4 to Rs 37.7 and the cost of non-vegetarian thali has risen from Rs 55.6 to Rs 66.8. ",
    content:"The price of tomato rose by 233% month-on-month to Rs 110/kg in July from Rs 33/kg in June. In retail markets, it has skyrocketed to Rs 250 per kg, making it more expensive than petrol (Rs 97 per litre in Delhi).Of the 34% rise in the cost of a vegetarian thali, 25% can be attributed solely to the price of tomato, which rose 233% month-on-month to Rs 110/kg in July from Rs 33/kg in June, said the Crisil report.The price of tomatoes in retail markets has skyrocketed to Rs 250 per kg, making it more expensive than petrol (Rs 97 per litre in Delhi).",
    category:"ToppostsFood",
    
},
{
    id:9,
    image:"https://media.cnn.com/api/v1/images/stellar/prod/181127113434-39-50-sweets-travel-sticky-rice-with-mango.jpg?q=w_4743,h_2668,x_0,y_0,c_fill/w_1280",
    heading:"Sticky Rice with Mango, Thailand",
    description:"A ripe, tender dish of sticky rice with mango is among the world’s most perfect desserts.",
    content:"This Thai dessert of glutinous sticky rice, seasoned with salty-sweet coconut milk and served with tender, fragrant slices of mango, will be irresistible.This Thai dessert is very similar to a lot of Filipino glutinous-rice based desserts so I wanted to add some ube to create a fusion of both Filipino and Thai flavours.This version is like a fusion of both Filipino and Thai cuisine. Glutinous rice-based offerings such as ‘kakanin’ are very popular in Filipino cuisine, which is why Thailand’s famous mango with sticky rice is very suited to the Filipino palate.",
    category:"Food",  
},
{
    id:10,
    image:"https://media.cnn.com/api/v1/images/stellar/prod/181127105042-06-50-sweets-travel-sour-cherry-pie.jpg?q=w_3101,h_1744,x_0,y_0,c_fill/w_1280",
    heading:"Sour Cherry Pie, Midwestern United States",
    description:"Slice into the crispy top of a sour cherry pie, and the brilliant filling might come as a shock – it’s an electric color that seems more likely to be harvested from a can than a tree.",
    content:"Sour Cherry Pies have the capability of giving you that warm fuzzy feeling before you even bite into this gorgeous dessert. Slice into the crispy top of a sour cherry pie, and the brilliant filling might come as a shock – it’s an electric color that seems more likely to be harvested from a can than a tree. That electric red comes from the tart Montmorency cherries that are the classic filling for this pie. Since the tender fruits are more perishable than their sweeter cousins, if you live outside the Midwest or Northeast United States you might never have seen one. Sour cherries have plenty of acid to counter-balance the sugar in the filling, and they’re rich in tannins, too. It’s a hint of complexity that put this fruit pie over the top as one of the best in America. Wrap yourself in a blanket, make yourself some hot cocoa, and bite into the cherry pie and you’ll feel Love is all around!",
    category:"Food",
},
{
    id:11,
    image:"https://i.ytimg.com/vi/rFUoXOiskqA/maxresdefault.jpg",
    heading:"Tender Coconut Shake:A rich, creamy cool drink made by blending chilled milk with tender coconut",
    content:"Smooth creamy Nestlé A+ Milkshake using coconut, cream and coconut water. One of the best summer refreshing shake packed with vitamins and minerals. Boost your energy and keep the heat at bay.Elaneer Milkshake is a popular drink in South India. It is full of cooling and energising properties as well as important nutrients. This delicious traditional milkshake is a must-try in summer.Tender coconut is a natural rehydrating drink that has no added chemicals or harmful ingredients. It is the best drink to choose any day. It is very effective in keeping you hydrated.",
    category:"ToppostsFood",
},
{
    id:12,
    image:"https://images.squarespace-cdn.com/content/v1/614a009b2cb9af680ff625f7/1633976217209-5BR28497YSLNVM56E7D6/image-asset-2.jpeg",
    heading:"Japanese Cheesecake",
    description:"Japanese cheesecake is also known as a Japanese cotton cheesecake or a Japanese soufflé' cheesecake.It is a mix between a regular cheesecake (Basque or NY Style) mixed with a chiffon cake.",
    content:"Japanese cheesecake, also known as soufflé-style cheesecake, cotton cheesecake, or light cheesecake, is a variety of cheesecake that is usually lighter in texture and less sweet than North American-style cheesecakes.It has a characteristically wobbly and airy texture, similar to a soufflé when fresh out of the oven and a chiffon cake-like texture when chilled.The recipe was created by Japanese chef Tomotaro Kuzuno, who was inspired by a local käsekuchen cheesecake (a German variant) during a trip to Berlin in the 1960s.It is less sweet and has fewer calories than standard Western-style cheesecakes, containing less cheese and sugar. The cake is made with cream cheese, butter, sugar, and eggs. Similar to chiffon cake or soufflé, Japanese cheesecake has a fluffy texture produced by whipping egg white and egg yolk separately.",
    category:"Food",
},
{
    id:13,
    image:"https://i.ytimg.com/vi/c0PQz7TF7RQ/maxresdefault.jpg",
    heading:"Pesarattu, Andhra Pradesh",
    description:"The name pesarattu sounds quite exotic, which, in fact, it is. In Telugu, pesarattu literally means a “moong dal dosa,” which is a South Indian crepe made of rice and mung beans.",
    content:"Pesarattu, pesara attu, pesara dosa, or cheeldo is a crepe-like bread, originating in Andhra Pradesh, India, that is a variety of dosa. It is made with green gram batter, but, unlike a typical dosa, it does not contain urad dal. Pesarattu is eaten as breakfast and as a snack in Andhra Pradesh.It is typically served with ginger chutney or peanut chutney or tamarind chutney. Green chilies, ginger and onions are used in variants.A pesarattu stuffed with upma is known as upma pesarattu. It is popular in Andhra Pradesh cities. Upma pesarattu is a favourite in the Coastal Andhra, region especially the West Godavari District, East Godavari District, Krishna district, Guntur District especially in Planadu regions of Guntur District, Guntur and Vijayawada cities and Visakhapatnam District.",
    category:"Food",
},
{
    id:14,
    image:"https://images.immediate.co.uk/production/volatile/sites/30/2015/03/lentil-sweet-potato-curry-b4d0658.jpg?quality=90&webp=true&fit=975,649",
    heading:"Erissery or pumpkin and lentil curry",
    description:"This is a popular curry in Kerala, made from either raw plantains or sliced yams. It also usually includes slightly sweet pumpkin that has been boiled in water with salt.",
    content:"Erissery is one of the famous dishes of Kerala which is savoured by travellers as well as local people in Kerala. A hit in every kitchen of Kerala, this curry is made from either raw plantains or sliced yams. It is typically prepared by boiling slightly sweet pumpkins with salt, chillies or pepper, dried lentils, grated coconut, turmeric powder, cumin seeds and garlic, and is served on a bed of rice once cooked. A favourite Kerala food item on the menu of religious festivals like Onam, Erissery provides the perfect culinary for foodies who are always on the lookout for new flavours!",
    category:"Food",
},
{
    id:15,
    image:"https://curlytales.com/wp-content/uploads/2018/03/slide-pull-1.jpg",
    heading:"Monster Deep Dish Pizza – Baked And Wired",
    description:"Baked And Wired is known for its monster deep dish pizzas that are prepared Chicago style.",
    content:"Baked And Wired is known for its monster deep dish pizzas that are prepared Chicago style.Love cheese? You will love Pune’s new pizzeria by the name of Baked And Wired. Located at Kalyani Nagar, it serves some of the cheesiest pizzas known to mankind. After their delivery service turned into a huge hit, Baked And Wired has opened up their newest outlet. If you wanna have an affair with oodles of cheese on a pizza, you’re at the right place.This outlet never fails to astonish pizza lovers from the city with their monster pizza. With their multiple varieties of toppings, they surely make an offer you can’t resist.",
    category:"Food",
},
{
    id:16,
    image:"https://images.slurrp.com/prod/articles/4b56xdsvk5s.webp",
    heading:"Ragi Mudde",
    description:"Ragi is one of the staple foods in Karnataka. Ragi mudde or soft finger millet balls are made of ragi flour and water.",
    content:"More a technique than a recipe, Ragi Mudde are healthy balls made from finger millet flour and water. They are a delicacy and a staple food mainly in Karnataka and in some parts of Tamil Nadu and Andhra Pradesh. These delicious and nutritious balls could be considered the original “protein bites,” intended to keep farmers and working folks full during the day.Ragi Mudde is a simple but wholesome healthy food of soft balls made with two basic ingredients – finger millet flour and water.Finger millet is called as Ragi in Kannada, Mandua in Hindi, Nachni in Marathi and Ragulu in Telugu. The word “Mudde” means lump in Kannada language.If you have ever before attempted to make this hearty peasant food before, you may have had the unfortunate result of an undercooked or floury tasting ball at the end.",
    category:"Food",
},
{
    id:17,
    image:"https://www.scrolldroll.com/wp-content/uploads/2021/04/Enduri_Pitha-traditional-dishes-from-Odisha-768x512.jpg",
    heading:"Pitha",
    description:"There are quite a few unique varieties of pithas (boiled or fried cakes) that are prepared in Odisha.Pitha (Haldi Patra Pitha) prepared during Prathamasthmi.",
    content:"Pithas are a variety of food similar to pancakes, dumplings or fritters, originating from the Indian subcontinent, common in Bangladesh and India. Pitha can be sweet or savoury, and usually made from a dough or batter, which is then steamed, fried or griddled. Very few varieties are oven-baked or boiled, and most are unleavened and cooked on a stovetop (or equivalent). Some versions may have a filling, garnish, or sauce. Few may be set or shaped after cooking. They are typically eaten as a snack with chai, or as treats during special occasions (similar to mithai).",
    category:"Food",
},
{
    id:18,
    image:"https://adventures.com/media/19161/canadian-poutine-food-dish.jpg?anchor=center&mode=crop&width=970&height=645&rnd=132632868080000000&quality=80&format=webp",
    heading:"Poutine",
    description:"You'll find poutine on most Canadian menus, but its real home is in Quebec. The savory dish combines fries, cheese, and gravy.",
    content:"Poutine is a dish of french fries and cheese curds topped with a brown gravy. It emerged in Quebec, in the late 1950s in the Centre-du-Québec region, though its exact origins are uncertain and there are several competing claims regarding its invention. For many years, it was used by some to mock Quebec society. Poutine later became celebrated as a symbol of Québécois culture and the province of Quebec. It has long been associated with Quebec cuisine, and its rise in prominence has led to its growing popularity throughout the rest of Canada. Annual poutine celebrations occur in Montreal, Quebec City, and Drummondville, as well as Toronto, Ottawa, New Hampshire, and Chicago. It has been called 'Canada's national dish', though some critics believe this labelling represents cultural appropriation of the Québécois or Quebec's national identity.",
    category:"FSide",
},
{
    id:19,
    image:"https://st5.depositphotos.com/5653638/62941/i/450/depositphotos_629410112-stock-photo-chole-bhature-north-indian-food.jpg",
    heading:"Chole bhature",
    description:"At its core, chole bhature is a combination of two dishes: chole - a spicy chickpea curry, and bhature - a type of fried bread made with maida flour.",
    content:"Chole Bhature also known as Chana Bhatura is one of the most popular Punjabi dish liked almost all over India. Chole stands for a spiced tangy chickpea curry and Bhatura is a soft and fluffy fried leavened bread. Chola Bhatura always make for a delicious and filling meal. In this recipe post, I have included the step-by-step pictorial of making both the chana curry as well as a quick bhatura that is made without yeast.Chana Bhatura is a spicy, tasty and a filling dish. I have eaten this dish at many places in Punjab and Delhi. Each restaurants or dhaba (eateries on highways) have their own flavors and taste in the chickpea curry.",
    category:"FSide",
}]
module.exports = {bollywood, hollywood, fitness, food}